import "@/styles/globals.css";
import styles from "./layout.module.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";

// components
import Navigation from "./Navigation";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "600", "800"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navigation />
        <main className={styles.main}>{children}</main>
      </body>
    </html>
  );
}
