"use client";

import { useContext } from "react";
import ThemeContextProvider, { ThemeContext } from "@/contexts/ThemeContext";
import "@/styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function UnloggedLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeContextProvider>{children}</ThemeContextProvider>
    </html>
  );
}
